#spring.application.name=jwt_auth
#
#spring.datasource.url=jdbc:postgresql://localhost:5433/jwt_auth_db
#spring.datasource.username=postgres
#spring.datasource.password=newpassword
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#
## JPA/Hibernate Properties
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#
##What these lines do for you:
##spring.jpa.database=postgresql: This tells Hibernate exactly what database syntax to use. It fixes your exact Unable to determine Dialect error.
##spring.jpa.hibernate.ddl-auto=update: This tells Hibernate to automatically create or update your database tables in PostgreSQL to match your Java @Entity classes. You won't have to write manual SQL tables yourself.
##spring.jpa.show-sql=true: This prints the database queries into your console logs. This is highly useful for checking if your login system is actually talking to the database.
#
## Enables a cleaner, modern layout theme for your documentation page
#springdoc.swagger-ui.layout=BaseLayout

spring.application.name=jwt_auth

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.layout=BaseLayout
